nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']

    paths:

        '^/api/': # Aplica CORS para todas las rutas que comiencen con /api
            allow_origin: [ 'http://localhost:4200']
            allow_headers: [ 'Content-Type', 'Authorization' ]
            allow_methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ]
            allow_credentials: true

